### PR TITLE
Fix relative path redirects urlencoding query parameters, fixes #1436

### LINKED ISSUE #1436: Following URL redirect url-encodes the query parameters resulting in a bad request
In the ratpack HttpClient implementation when we get a 301 response, we read the `Location` header as a full raw string. Then when creating the new URI we are url encoding the full string, which results in the `?` being percent encoded. 

The bug specifically happens here https://github.com/ratpack/ratpack/blob/141fa01f4e42781cf2120ddb53a16ba16fced69a/ratpack-core/src/main/java/ratpack/http/client/internal/RequestActionSupport.java#L258

To fix this we would need to parse the `Location` header to at least separate out the query parameters and pass them to the URI constructor.

### PR DESCRIPTION
**Pull request by fromanator**
This change is [Reviewable](https://reviewable.io/reviews/ratpack/ratpack/1437)

### CODE REVIEW

File: ratpack-core/src/test/groovy/ratpack/http/client/HttpClientRedirectionSpec.groovy [hunk 1]
```diff
@@ -53,6 +53,73 @@ class HttpClientRedirectionSpec extends BaseHttpClientSpec {
...
+    }
+
+    then:
+    text == "value1value2"
+
+    where:
+    pooled << [true, false]
+  }
+
+  def "can follow a relative redirect get request with query parameters"() {
```
Comment (fromanator) [inline ratpack-core/src/test/groovy/ratpack/http/client/HttpClientRedirectionSpec.groovy]: Confirmed that with the code without my fix would break here, the application would return a 404 because the `?` was being percent encoded so path matching would break. After my fix this does work.

File: ratpack-core/src/test/groovy/ratpack/http/client/HttpClientRedirectionSpec.groovy [hunk 2]
```diff
@@ -53,6 +53,73 @@ class HttpClientRedirectionSpec extends BaseHttpClientSpec {
     pooled << [true, false]
   }
 
+  def "can follow redirect get request with query parameters"() {
```
Comment (fromanator) [inline ratpack-core/src/test/groovy/ratpack/http/client/HttpClientRedirectionSpec.groovy]: Added just to be sure that the changes I made for the absolute URI didn't break anything, old code also passed this test.

Comment (beckje01) [reply ratpack-core/src/test/groovy/ratpack/http/client/HttpClientRedirectionSpec.groovy]: :+1:

File: ratpack-core/src/test/groovy/ratpack/http/client/HttpClientRedirectionSpec.groovy (hunk 1 above)
Comment (beckje01) [reply ratpack-core/src/test/groovy/ratpack/http/client/HttpClientRedirectionSpec.groovy]: :+1:
